[project]
name = "movie-recommender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipynb>=0.5.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
